# Generated by Django 5.2.17 on 2026-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
