# Generated by Django 5.2.17 on 2026-09-12 19:52

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="JPEG or PNG, up to 2 MB and 4096 by 4096 pixels.",
                upload_to="profiles/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    ),
                    accounts.validators.validate_photo,
                ],
            ),
        ),
    ]
