# Generated by Django 5.2.17 on 2026-09-12 20:13

import courses.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_enrolment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "file",
                    models.FileField(
                        help_text="PDF, JPEG or PNG, up to 10 MB. Images: at most 4096 by 4096 pixels.",
                        upload_to="course_materials/",
                        validators=[courses.validators.validate_material],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-pk"],
            },
        ),
    ]
