# Generated by Django 5.2.17 on 2026-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
